### ISSUE TITLE
Sirens from megapack not working

### ISSUE THREAD

**Issue by MoubyCT** [TrevorBarns/luxart-vehicle-control-extras#6]
All the sirens from FIB and down do not work ingame. The rest works fine.
eg; siren table numbers 39 to 50 do not stream the sound.
SAS is installed.

--[[39]]  { Name = 'CGOLD-HORN',       String = 'OISS_SSA_VEHAUD_FIB_NEW_HORN',              Ref = 'OISS_SSA_VEHAUD_FIB_NEW_SOUNDSET'}, 
--[[40]]  { Name = 'CGOLD-WAIL',       String = 'OISS_SSA_VEHAUD_FIB_NEW_SIREN_ADAM',        Ref = 'OISS_SSA_VEHAUD_FIB_NEW_SOUNDSET'},
--[[41]]  { Name = 'CGOLD-YELP',       String = 'OISS_SSA_VEHAUD_FIB_NEW_SIREN_BOY',         Ref = 'OISS_SSA_VEHAUD_FIB_NEW_SOUNDSET'}, 
--[[42]]  { Name = 'CGOLD-PRIORITY',   String = 'OISS_SSA_VEHAUD_FIB_NEW_SIREN_CHARLES',     Ref = 'OISS_SSA_VEHAUD_FIB_NEW_SOUNDSET'}, 
--[[43]]  { Name = 'CGOLD-SWEEP',      String = 'OISS_SSA_VEHAUD_FIB_NEW_SIREN_DAVID',       Ref = 'OISS_SSA_VEHAUD_FIB_NEW_SOUNDSET'}, 
--[[44]]  { Name = 'CGOLD-SWEEP3',     String = 'OISS_SSA_VEHAUD_FIB_NEW_SIREN_EDWARD',      Ref = 'OISS_SSA_VEHAUD_FIB_NEW_SOUNDSET'}, 
--[[45]]  { Name = 'FIRE HORN',        String = 'OISS_SSA_VEHAUD_LSFD_NEW_HORN',             Ref = 'OISS_SSA_VEHAUD_LSFD_NEW_SOUNDSET'},
--[[46]]  { Name = 'POWERCALL',        String = 'OISS_SSA_VEHAUD_LSFD_NEW_SIREN_ADAM',       Ref = 'OISS_SSA_VEHAUD_LSFD_NEW_SOUNDSET'},
--[[47]]  { Name = 'Q-COAST',          String = 'OISS_SSA_VEHAUD_LSFD_NEW_SIREN_BOY',        Ref = 'OISS_SSA_VEHAUD_LSFD_NEW_SOUNDSET'},
--[[48]]  { Name = 'Q-HIGH',           String = 'OISS_SSA_VEHAUD_LSFD_NEW_SIREN_CHARLES',    Ref = 'OISS_SSA_VEHAUD_LSFD_NEW_SOUNDSET'},
--[[49]]  { Name = 'Q-MID',            String = 'OISS_SSA_VEHAUD_BCFD_NEW_SIREN_DAVID',      Ref = 'OISS_SSA_VEHAUD_BCFD_NEW_SOUNDSET'},
--[[50]]  { Name = 'Q-MID2',           String = 'OISS_SSA_VEHAUD_BCFD_NEW_SIREN_EDWARD',     Ref = 'OISS_SSA_VEHAUD_BCFD_NEW_SOUNDSET'},

**Comment by TrevorBarns** [comment]
Duplicate issue: https://github.com/TrevorBarns/luxart-vehicle-control/issues/72
